"use client";

import { useState } from "react";
import { ActionConfirm } from "./ActionConfirm";
import type { RefundMethod } from "@/lib/policies/returns";

/**
 * ReturnCard Component
 *
 * GenUI component for displaying return options in chat stream.
 * Features:
 * - Displays personalized return options based on policy engine
 * - Auto-approval badge for eligible returns
 * - Selection triggers ActionConfirm for final confirmation
 * - Dark mode support
 * - Touch-friendly tap targets (44px minimum)
 * - Accessible (ARIA labels, keyboard navigation)
 *
 * @file components/genui/return-card.tsx
 */

// ============================================================================
// Type Definitions
// ============================================================================

/**
 * Return option structure
 *
 * Matches the ReturnOption type from policy engine.
 */
export interface ReturnOption {
  method: RefundMethod;
  label: string;
  description: string;
  value: number;
  eta?: string;
}

/**
 * ReturnCard component props
 */
export interface ReturnCardProps {
  /** Order details */
  order: {
    id: string;
    total: number;
    items: Array<{ name: string; productId?: string }>;
  };
  /** Available return options from policy engine */
  options: ReturnOption[];
  /** Whether return is auto-approved (no manual review) */
  autoApproved: boolean;
  /** Customer's reason for return */
  reason: string;
  /** Items being returned */
  items: Array<{ productId: string; quantity: number }>;
  /** Compact summary for AIState (~60 tokens) */
  summary?: string;
}

// ============================================================================
// Component Implementation
// ============================================================================

/**
 * ReturnCard component for return option selection
 *
 * Displays return options generated by the policy engine.
 * When user selects an option, shows ActionConfirm for final confirmation.
 *
 * @example
 * ```tsx
 * <ReturnCard
 *   order={{ id: "ORD123", total: 11990, items: [{ name: "Sony WH-1000XM5" }] }}
 *   options={[
 *     { method: 'replacement', label: 'Replacement', description: '...', value: 11990 }
 *   ]}
 *   autoApproved={true}
 *   reason="defective"
 *   items={[{ productId: 'prod_123', quantity: 1 }]}
 * />
 * ```
 */
export function ReturnCard({
  order,
  options,
  autoApproved,
  reason,
  items,
  summary,
}: ReturnCardProps) {
  const [selectedOption, setSelectedOption] = useState<ReturnOption | null>(
    null
  );
  const [showConfirm, setShowConfirm] = useState(false);

  // Show confirmation dialog when option is selected
  if (showConfirm && selectedOption) {
    return (
      <ActionConfirm
        title="Confirm Return"
        lines={[
          { label: "Order", value: order.id },
          { label: "Item", value: order.items[0]?.name ?? "Unknown item" },
          {
            label: "Return Method",
            value: selectedOption.label,
          },
          {
            label: "Refund Amount",
            value: `₹${selectedOption.value.toLocaleString("en-IN")}`,
          },
          {
            label: "Reason",
            value: reason.replace("_", " "),
          },
        ]}
        confirmLabel="Confirm Return"
        cancelLabel="Cancel"
        isDanger={selectedOption.method === "refund"}
        onConfirm={async () => {
          // TODO: Call actual return API in Phase 2
          // await initiateReturnAPI({
          //   orderId: order.id,
          //   items,
          //   method: selectedOption.method,
          //   reason,
          // });
          console.log("[Return Initiated]", {
            orderId: order.id,
            method: selectedOption.method,
            items,
          });
        }}
        onCancel={() => {
          setShowConfirm(false);
          setSelectedOption(null);
        }}
        onSuccess={() => {
          // Optional: Trigger success callback
          console.log("[Return Success] Return initiated successfully");
        }}
      />
    );
  }

  // Show return options selection
  return (
    <div className="rounded-xl border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-800 overflow-hidden shadow-sm">
      {/* Header */}
      <div className="p-4 border-b border-zinc-200 dark:border-zinc-700 bg-zinc-50 dark:bg-zinc-900/50">
        <div className="flex items-start justify-between gap-4">
          <div>
            <h3 className="font-semibold text-zinc-900 dark:text-zinc-100">
              Return Options for Order {order.id}
            </h3>
            <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-1">
              Reason:{" "}
              <span className="capitalize">{reason.replace("_", " ")}</span>
              {autoApproved && (
                <span className="ml-2 inline-flex items-center gap-1 text-xs font-medium text-green-600 dark:text-green-400">
                  <svg
                    className="w-3.5 h-3.5"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    aria-hidden="true"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M5 13l4 4L19 7"
                    />
                  </svg>
                  Auto-approved
                </span>
              )}
            </p>
          </div>
          <div className="text-right">
            <p className="text-xs text-zinc-500 dark:text-zinc-400">
              Order Total
            </p>
            <p className="font-semibold text-zinc-900 dark:text-zinc-100">
              ₹{order.total.toLocaleString("en-IN")}
            </p>
          </div>
        </div>
      </div>

      {/* Options */}
      <div className="divide-y divide-zinc-200 dark:divide-zinc-700">
        {options.map((option) => (
          <button
            key={option.method}
            onClick={() => {
              setSelectedOption(option);
              setShowConfirm(true);
            }}
            className="w-full p-4 text-left hover:bg-zinc-50 dark:hover:bg-zinc-700/50 transition-colors focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-500"
            type="button"
            aria-label={`Select ${option.label} option`}
          >
            <div className="flex justify-between items-start gap-4">
              <div className="flex-grow">
                <div className="flex items-center gap-2">
                  <p className="font-medium text-zinc-900 dark:text-zinc-100">
                    {option.label}
                  </p>
                  {option.method === "store_credit" && option.value > order.total && (
                    <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400">
                      +₹{(option.value - order.total).toLocaleString("en-IN")} bonus
                    </span>
                  )}
                </div>
                <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-1">
                  {option.description}
                </p>
              </div>
              <div className="text-right flex-shrink-0">
                <p className="font-semibold text-zinc-900 dark:text-zinc-100">
                  ₹{option.value.toLocaleString("en-IN")}
                </p>
                {option.eta && (
                  <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-1">
                    {option.eta}
                  </p>
                )}
              </div>
            </div>
          </button>
        ))}
      </div>
    </div>
  );
}

export default ReturnCard;
