import { memo } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { colors, font, spacing, radius, shadow } from '../../lib/theme';

type Order = { id: string; status: keyof typeof colors.status; total: number; orderDate: string; trackingNumber?: string };

const StatusBadge = memo(({ status }: { status: keyof typeof colors.status }) => { const scheme = colors.status[status] ?? { bg: colors.surfaceOffset, text: colors.textMuted }; return <View style={[s.badge, { backgroundColor: scheme.bg }]}><Text style={[s.badgeText, { color: scheme.text }]}>{status}</Text></View>; });
const OrderRow = memo(({ order, index }: { order: Order; index: number }) => { const date = new Date(order.orderDate); const fmt = date.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }); return (<Animated.View style={s.row} entering={FadeInDown.delay(index * 60).springify()}><View style={s.rowTop}><Text style={s.orderId} numberOfLines={1}>#{order.id.slice(-8).toUpperCase()}</Text><StatusBadge status={order.status} /></View><View style={s.rowBottom}><Text style={s.date}>{fmt}</Text><Text style={s.amount}>₹{order.total.toLocaleString('en-IN')}</Text></View>{order.trackingNumber && <Text style={s.tracking}>Tracking: {order.trackingNumber}</Text>}</Animated.View>); });

export const OrderList = memo(({ orders }: { orders: Order[] }) => {
  if (orders.length === 0) return <View style={s.empty}><Text style={s.emptyIcon}>📦</Text><Text style={s.emptyTitle}>No orders yet</Text><Text style={s.emptySub}>Your order history will appear here</Text></View>;
  return (<View style={s.container}><Text style={s.heading}>Recent Orders ({orders.length})</Text>{orders.map((o, i) => <OrderRow key={o.id} order={o} index={i} />)}</View>);
});
const s = StyleSheet.create({ container: { gap: spacing[2] }, heading: { fontSize: font.size.base, fontWeight: '600', color: colors.textMuted, fontFamily: font.family, marginBottom: spacing[2] }, row: { backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing[4], gap: spacing[2], ...shadow.sm }, rowTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, orderId: { fontSize: font.size.base, fontWeight: '700', color: colors.text, fontFamily: font.family }, badge: { paddingHorizontal: spacing[2], paddingVertical: spacing[1], borderRadius: radius.full }, badgeText: { fontSize: font.size.xs, fontWeight: '600', fontFamily: font.family }, rowBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, date: { fontSize: font.size.sm, color: colors.textMuted, fontFamily: font.family }, amount: { fontSize: font.size.lg, fontWeight: '700', color: colors.primary, fontFamily: font.family }, tracking: { fontSize: font.size.xs, color: colors.textMuted, fontFamily: font.family }, empty: { alignItems: 'center', padding: spacing[8] }, emptyIcon: { fontSize: 40, marginBottom: spacing[2] }, emptyTitle: { fontSize: font.size.lg, fontWeight: '600', color: colors.text, fontFamily: font.family }, emptySub: { fontSize: font.size.sm, color: colors.textMuted, fontFamily: font.family, marginTop: spacing[2] } });
