import { useState, memo } from 'react';
import { View, Text, TouchableOpacity, StyleSheet } from 'react-native';
import Animated, { FadeInDown, useSharedValue, useAnimatedStyle, withSpring } from 'react-native-reanimated';
import * as Haptics from 'expo-haptics';
import { colors, font, spacing, radius, shadow } from '../../lib/theme';

type Option = { type: string; label: string; description: string; amount?: number };
const OptionCard = memo(({ option, selected, onPress }: { option: Option; selected: boolean; onPress: () => void }) => { const scale = useSharedValue(1); const pressStyle = useAnimatedStyle(() => ({ transform: [{ scale: scale.value }] })); const handlePress = async () => { scale.value = withSpring(0.96, {}, () => { scale.value = withSpring(1, { damping: 20 }) }); await Haptics.selectionAsync(); onPress(); }; return (<TouchableOpacity onPress={handlePress} activeOpacity={0.85}><Animated.View style={[s.optCard, selected && s.optCardSelected, pressStyle]}><View style={s.optTop}><Text style={[s.optLabel, selected && s.optLabelSelected]}>{option.label}</Text>{selected && <View style={s.checkCircle}><Text style={s.checkMark}>✓</Text></View>}</View><Text style={s.optDesc}>{option.description}</Text>{option.amount != null && <Text style={[s.optAmount, selected && s.optAmountSelected]}>₹{option.amount.toLocaleString('en-IN')}</Text>}</Animated.View></TouchableOpacity>); });

export const ReturnCard = memo(({ eligible, orderId, options, onSelect }: { eligible: boolean; orderId: string; options: Option[]; onSelect: (type: string) => void }) => { const [selected, setSelected] = useState<string | null>(null); if (!eligible) return (<Animated.View style={s.ineligible} entering={FadeInDown.springify()}><Text style={s.ineligibleIcon}>⏰</Text><Text style={s.ineligibleTitle}>Return window closed</Text><Text style={s.ineligibleSub}>Order #{orderId.slice(-8).toUpperCase()} is outside the 7-day return policy.</Text></Animated.View>); return (<Animated.View style={s.container} entering={FadeInDown.springify()}><Text style={s.heading}>Choose a return option</Text><Text style={s.sub}>Order #{orderId.slice(-8).toUpperCase()}</Text><View style={s.options}>{options.map((opt) => (<OptionCard key={opt.type} option={opt} selected={selected === opt.type} onPress={() => { setSelected(opt.type); onSelect(opt.type); }} />))}</View></Animated.View>); });
const s = StyleSheet.create({ container: { backgroundColor: colors.surface, borderRadius: radius.xl, padding: spacing[5], gap: spacing[4], ...shadow.md }, heading: { fontSize: font.size.lg, fontWeight: '700', color: colors.text, fontFamily: font.family }, sub: { fontSize: font.size.sm, color: colors.textMuted, fontFamily: font.family, marginTop: -spacing[2] }, options: { gap: spacing[3] }, optCard: { borderRadius: radius.lg, padding: spacing[4], borderWidth: 1.5, borderColor: colors.border, backgroundColor: colors.bg, gap: spacing[2] }, optCardSelected: { borderColor: colors.primary, backgroundColor: colors.primaryHighlight }, optTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, optLabel: { fontSize: font.size.base, fontWeight: '700', color: colors.text, fontFamily: font.family }, optLabelSelected: { color: colors.primary }, optDesc: { fontSize: font.size.sm, color: colors.textMuted, fontFamily: font.family }, optAmount: { fontSize: font.size.lg, fontWeight: '700', color: colors.text, fontFamily: font.family }, optAmountSelected: { color: colors.primary }, checkCircle: { width: 22, height: 22, borderRadius: radius.full, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, checkMark: { color: '#fff', fontSize: 12, fontWeight: '700' }, ineligible: { backgroundColor: colors.warningBg, borderRadius: radius.xl, padding: spacing[6], alignItems: 'center', gap: spacing[3] }, ineligibleIcon: { fontSize: 36 }, ineligibleTitle: { fontSize: font.size.lg, fontWeight: '700', color: colors.warning, fontFamily: font.family }, ineligibleSub: { fontSize: font.size.sm, color: colors.textMuted, fontFamily: font.family, textAlign: 'center' } });
